fix(TagsInput): add status validation and other fixes
lumada-design/hv-uikit-react pull request #2654
Opened 2022-02-01 15:11 UTC by plagoa

- update `onChange` signature
- update type definition to extend from `HvInputProps` instead of `HvBaseInputProps`
- Remove max-width limit on tags
- Add outline on focus
- Add error message and status validation
- Disable default behavior when enter is pressed to add a tag to prevent submiting a form where the component might be included

2022-02-01 17:09 UTC, plagoa commented
@eliofreitas please take a look. I added a new story to showcase using the `TagsInput` component inside a form.

2022-02-02 10:59 UTC, eliofreitas requested changes

2022-02-02 10:59 UTC, eliofreitas commented on packages/core/src/TagsInput/TagsInput.js
> +              onChange?.(undefined, newTagsArr);
In here we could sent the event coming from the keydown

2022-02-02 11:11 UTC, eliofreitas approved these changes

2022-02-02 13:56 UTC, francisco-guilherme approved these changes

2022-02-02 15:43 UTC, diogofscmariano requested changes
I would adjust the same. The input should have the required option and actually display an error. Otherwise just remove it. Regarding the tagsInput, we should support the required option, having the * in the label and at least implement that in the sample, since this is a form field.

2022-02-02 20:06 UTC, plagoa commented
@diogofscmariano added the required property and updated the story to include that.

2022-02-02 22:09 UTC, diogofscmariano approved these changes

2022-02-02 22:14 UTC, merged