feat(tag-input): adding on blur callback
lumada-design/hv-uikit-react pull request #2676
Opened 2022-02-14 13:57 UTC by eliofreitas

2022-02-14 14:01 UTC, plagoa approved these changes

2022-02-14 14:57 UTC, nantunes requested changes
It shouldn't add empty tags.
![image](https://user-images.githubusercontent.com/209365/153887945-42fab401-e690-4508-803a-0989fe5e7828.png)

2022-02-14 14:59 UTC, nantunes requested changes
Also, simply clicking inside this component trigger the blur... You can't event delete a tag.
https://user-images.githubusercontent.com/209365/153888219-5c3056a5-f397-496a-a10d-62b8ed7f19a3.mov

2022-02-15 17:36 UTC, francisco-guilherme approved these changes

2022-02-15 17:38 UTC, plagoa approved these changes

2022-02-15 17:40 UTC, nantunes approved these changes

2022-02-15 17:40 UTC, merged