feat(Loading): adding a progress bar mode
lumada-design/hv-uikit-react pull request #2679
Opened 2022-02-17 16:44 UTC by plagoa

Notes:
- This only features the progress bar in a determinate mode. I'm a bit unsure as to what the behavior in undeterminate mode should be (I'd assume an infinite looping bar but the specs don't really mention anything about it);
- This is borderline what I'm confortable with as to making a component have some conditional rendering inside, maybe the progress part should be moved to a specific `ProgressBar` component inside the `Loading` component;
- I updated the `FileUpload` component to use this the `Loading` component in progress mode instead of the old internal logic;

2022-03-29 09:53 UTC, francisco-guilherme approved these changes
Great Job 👍

2022-03-29 10:30 UTC, hyorran approved these changes

2022-03-29 10:54 UTC, eliofreitas requested changes
Great work, I left some small comments nothing to worry

2022-03-29 10:54 UTC, eliofreitas commented on packages/core/src/Loading/Loading.d.ts
> +export default function HvLoading(props: HvLoadingProps): JSX.Element | null;
please include an enter at the end of the file to avoid this warning

2022-03-29 10:54 UTC, eliofreitas commented on packages/lab/src/ProgressBar/ProgressBar.js
> +    "aria-label": ariaLabel,
Explicitly defining the aria-label prop in here is not necessary because it is an standard html prop, so it is implicitly present in the `...others`

2022-03-29 10:54 UTC, eliofreitas commented on packages/lab/src/ProgressBar/ProgressBar.js
> +          {...(error && { "aria-invalid": true })}
I think the aria-invalid should be present where the aria-valuenow property  is placed, because that element is the one that the reader will see

2022-03-29 10:54 UTC, eliofreitas commented on packages/lab/src/ProgressBar/index.d.ts
> +
this file format is wrong we shouldn't include so much spaces

2022-03-29 14:48 UTC, eliofreitas requested changes

2022-03-29 14:48 UTC, eliofreitas commented on packages/lab/src/ProgressBar/ProgressBar.js
> +      aria-busy={clampedValue !== 100}
eliminate this is to be done by the user implementing the bar

2022-03-29 14:48 UTC, eliofreitas commented on packages/lab/src/ProgressBar/ProgressBar.js
> +      {...(error && { "aria-invalid": true })}
aria-invalid is only for form elements

2022-03-29 14:48 UTC, eliofreitas commented on packages/lab/src/ProgressBar/ProgressBar.js
> +        </span>
This logic could be fused with the label, and when it is in an undetermined state it hides the label but remains in the DOM

2022-03-29 14:48 UTC, eliofreitas commented on packages/lab/src/ProgressBar/ProgressBar.js
> +  const { className, classes, value = 0, error, undeterminate = false, ...others } = props;
error -> status:` invalid, valid, in progress ; "success", "in progress", "error"`. 

add a labelProp to spread generic values on the label of the element
should be typed as generic object in js
should be typed as div object in ts

2022-03-29 14:48 UTC, eliofreitas commented on packages/lab/src/ProgressBar/ProgressBar.js
> +  "aria-label": PropTypes.string,
this is no longer needed

2022-03-31 09:12 UTC, eliofreitas requested changes

2022-03-31 09:12 UTC, eliofreitas commented on packages/lab/src/ProgressBar/ProgressBar.js
> +        <div
ariaProps -> labelProps
see if we can eliminate the div and use only the `HvTypography`

2022-03-31 12:53 UTC, merged