feat(AppSwitcherPanel): promote component to core
lumada-design/hv-uikit-react pull request #2729
Opened 2022-04-07 14:24 UTC by plagoa

2022-04-11 16:11 UTC, eliofreitas requested changes

2022-04-11 16:11 UTC, eliofreitas commented on packages/core/src/AppSwitcherPanel/Action/Action.js
> +        // eslint-disable-next-line jsx-a11y/alt-text
Maybe we can avoid this disable by having the `description=""` as default or in alternative maybe using the role="presentation" as the image may not be critical for accessibility it is just decoration

2022-04-11 16:11 UTC, eliofreitas commented on packages/core/src/AppSwitcherPanel/Action/Action.js
> +  const { name, description, disabled, iconElement, iconUrl, url, target } = application;
maybe we could enhance the api with a `genericProp` to spread extra values to the components below

2022-04-19 14:28 UTC, francisco-guilherme approved these changes

2022-04-22 14:03 UTC, francisco-guilherme approved these changes

2022-04-22 14:03 UTC, merged