refactor(dotPagination): removed unnecessary code, added missing desc…
lumada-design/hv-uikit-react pull request #2738
Opened 2022-04-14 13:43 UTC by HQFOX

…ription HVUIKIT-6297

2022-04-14 14:06 UTC, eliofreitas requested changes
a couple of things to change:

- The commit should be fix, we want this in the change-log
- Remember to update the typescript definition, because the component is now extending from the hvRadiogroup

2022-04-19 14:26 UTC, francisco-guilherme approved these changes

2022-04-19 14:36 UTC, eliofreitas requested changes

2022-04-19 14:36 UTC, eliofreitas commented on packages/lab/src/DotPagination/DotPagination.js
> +          onChange={() => onPageChange(i)}
This onPageChange could also bubble up the Change event to the user 

`onChange={() => onPageChange(i)}` -> `onChange={(event) => onPageChange(event, i)}`

2022-04-19 14:36 UTC, eliofreitas commented on packages/lab/src/DotPagination/DotPagination.d.ts
> +  onPageChange?: (value: number) => void;
if the event is included this signature should also be updated

2022-04-20 09:46 UTC, eliofreitas approved these changes

2022-04-20 09:46 UTC, merged