fix(ProgressBar): corrected typescript definition, bubbled up role HV…
lumada-design/hv-uikit-react pull request #2748
Opened 2022-04-20 15:31 UTC by HQFOX

…UIKIT-5670

I also created a file "ProgressBarSimulator.js" so that the component used in testing and in the storybook to simulate the progress bar moving isn't repeated in two files.

Removed "magic strings" used in implementation for the status, now the corresponding values are stored in an object: statusCategories.

2022-04-20 16:24 UTC, hyorran commented
Just fix the description please.

2022-04-21 09:26 UTC, hyorran approved these changes

2022-04-21 16:17 UTC, eliofreitas requested changes

2022-04-21 16:17 UTC, eliofreitas commented on packages/lab/src/ProgressBar/ProgressBar.js
> +const statusCategories = { inProgress: "inProgress", completed: "completed", error: "error" };
You can include an `object.freeze({ inProgress: "inProgress", completed: "completed", error: "error" };)` to ensure this object remains consistent

2022-04-21 16:20 UTC, eliofreitas requested changes

2022-04-26 20:17 UTC, eliofreitas approved these changes

2022-04-26 20:17 UTC, merged