feat(SimpleGrid): created a new grid component
lumada-design/hv-uikit-react pull request #2755
Opened 2022-04-26 14:54 UTC by hyorran

2022-04-29 14:42 UTC, francisco-guilherme requested changes
Hi @hyorran, nice work overall.
Please do just some "design" improvements.
Increase the height of the containers and center the text horizontally and vertically.
Maybe add a few more samples to showcase different possibilities.

You can take a look at [this](https://mantine.dev/core/simple-grid/) just for reference.

2022-05-02 23:23 UTC, francisco-guilherme commented on packages/core/src/SimpleGrid/stories/SimpleGrid.stories.js
> +  title: "Foundation/SimpleGrid",
For now this story should be under Components.

2022-05-03 14:57 UTC, francisco-guilherme approved these changes

2022-05-03 15:06 UTC, HQFOX approved these changes

2022-05-03 15:08 UTC, merged