feat(Stack): create Stack component
lumada-design/hv-uikit-react pull request #2763
Opened 2022-05-04 10:30 UTC by plagoa

2022-05-04 16:16 UTC, francisco-guilherme approved these changes

2022-05-05 15:07 UTC, eliofreitas commented on packages/core/src/Stack/Stack.d.ts
> +  dividerProps: object;
check comment above

2022-05-05 15:17 UTC, eliofreitas requested changes

2022-05-05 15:17 UTC, eliofreitas commented on packages/core/src/Stack/Stack.js
> +  const getDirection = useCallback(() => {
This function doesn't receive any parameter, yet in line 52 some parameters are passed. However receiving the parameters may be good, if it receives parameters and avoids accessing the values from context the function could be pure and avoid the `useCallback`

2022-05-05 16:10 UTC, plagoa commented
@eliofreitas updated accordingly.

2022-05-05 16:26 UTC, eliofreitas approved these changes

2022-05-05 17:44 UTC, merged