feat(ActionsGeneric): add iconButton variant
lumada-design/hv-uikit-react pull request #2897
Opened 2022-08-18 16:44 UTC by zettca

Adds the possibility to have `ActionsGeneric` with buttons of variant `icon`.

Passing the `icon` prop isn't possible, because it's being used for something else. Also, this also implies that the label isn't visible (`aria-label` instead)

@lumada-design/imperial Let me know what you think.

2022-08-19 14:51 UTC, eliofreitas requested changes

2022-08-19 14:51 UTC, eliofreitas commented on packages/core/src/ActionsGeneric/ActionsGeneric.js
> +        {iconButtons ? renderedIcon : label}
To improve this, we could use the label as a condition to understand whether the user wants an icon button or a button with text and icon, by switching between` label == null ? renderedIcon : label`, with this we can avoid increasing a new prop to the API check: https://github.com/lumada-design/hv-uikit-react/commit/e2497590742d7cac812e2d4314c5f49357299b1a

2022-09-20 11:26 UTC, nantunes commented
...

2022-09-22 10:09 UTC, zettca commented
I've tried the suggested alternative, and it didn't quite work as intended.

Lead to https://github.com/lumada-design/hv-uikit-react/issues/2929

I'll close this for now, and reopen when I have the time to work on it and come up with another solution

2022-09-22 10:09 UTC, closed without merging