feat(Focus): add Focus component
lumada-design/hv-uikit-react pull request #3049
Opened 2023-01-09 11:08 UTC by plagoa

2023-01-09 17:22 UTC, HQFOX approved these changes

2023-01-10 09:07 UTC, francisco-guilherme commented on packages/core/src/components/Header/Navigation/MenuItem/MenuItem.tsx
> +import { isKeypress, KeyboardCodes } from "utils";
@plagoa `KeyboardCodes ` should be kept as camelCase, right?

2023-01-10 09:08 UTC, francisco-guilherme requested changes
@plagoa `KeyboardCodes` references should be kept as camelCase, right?

2023-01-10 09:32 UTC, francisco-guilherme approved these changes

2023-01-10 09:33 UTC, merged