feat(Wizard): add Wizard component to the Lab
lumada-design/hv-uikit-react pull request #3297
Opened 2023-04-26 17:19 UTC by plagoa

2023-04-27 14:58 UTC, stephaniegaspar requested changes

2023-04-27 14:58 UTC, stephaniegaspar commented on packages/lab/src/components/Wizard/WizardContent/WizardContent.tsx
> +        [index]: { ...child.props, form: {}, valid, touched: index === 0 },
You're not following the structure type `ContextProp`. Must be something like:

```
export type Tab = {
  valid?: boolean;
  mustValidate?: boolean;
  touched?: boolean;
  form?: any;
  children?: React.ReactNode;
}

export type ContextProp<T extends Tab>= {
  [tab in number]?: T;
};
```

2023-04-27 14:58 UTC, stephaniegaspar commented on packages/lab/src/components/Wizard/WizardActions/WizardActions.tsx
> +    updateContext(skippedContext);
Check [this line](https://github.com/lumada-design/hv-uikit-react/pull/3297/files#diff-1ef21b5620f3174f5bd0e8891d621e118da7505aa9b995cb17b2d953b36c8e9cR52).

2023-04-27 14:58 UTC, stephaniegaspar commented on packages/lab/src/components/Wizard/WizardContext/WizardContext.tsx
> +export type ContextProp = {
You may add a generic type to extend more properties for each tab like I proposed on [this line](https://github.com/lumada-design/hv-uikit-react/pull/3297/files#diff-1ef21b5620f3174f5bd0e8891d621e118da7505aa9b995cb17b2d953b36c8e9cR52).

2023-04-27 14:58 UTC, stephaniegaspar commented on packages/lab/src/components/Wizard/WizardContext/WizardContext.tsx
> +  updateContext: (values?: any) => void;
Prevent the use of `any`. Change it to `ContextProp`.

2023-04-27 14:58 UTC, stephaniegaspar commented on packages/lab/src/components/Wizard/WizardContext/WizardContext.tsx
> +      if (Object.entries(newContext).length > 0) {
You may want to clean the context when the dialog is closing and set it `{}`.

2023-04-27 14:58 UTC, stephaniegaspar commented on packages/lab/src/components/Wizard/WizardActions/WizardActions.tsx
> +    updateContext(skippedContext);
You should do something like this:
```
const skippedContext = Object.entries(context).reduce(
   (acc, [key, child]) => ({
      ...acc,
       [key]: {
         ...child,
         valid: child.valid !== false,
       }
   }),
   {}
);
```

2023-05-02 08:54 UTC, MEsteves22 commented on packages/lab/src/components/Wizard/WizardTitle/WizardTitle.tsx
> +  /** Current tab to check if it's last page or first to disable previous button and swap between next and submit button. */
Since these props are not necessary, we should remove them.

2023-05-02 08:55 UTC, MEsteves22 commented on packages/lab/src/components/Wizard/index.ts
> +export * from "./Wizard";
We should also export the classes.

2023-05-02 09:00 UTC, MEsteves22 commented on packages/lab/src/components/Wizard/WizardContainer/WizardContainer.tsx
> +  useEffect(() => {
We should remove this.

2023-05-02 10:49 UTC, MEsteves22 commented on packages/lab/src/components/Wizard/Wizard.tsx
> +  /** Title for the wizard. */
I believe we should use a more specific type than `any` here.

2023-05-02 10:49 UTC, MEsteves22 commented on packages/lab/src/components/Wizard/Wizard.tsx
> +  labels?: any; //HvWizardActionsProps["labels"] & HvWizardTitleProps["labels"];
I believe we should use a more specific type than `any` here.

2023-05-02 11:09 UTC, MEsteves22 commented on packages/core/src/components/Button/Button.styles.ts
> -  marginRight: theme.button.marginIconRight,
With these changes the buttons used on the bulk actions have more margin on the left.

2023-05-02 11:42 UTC, MEsteves22 commented
We also need to update the documentation since the wizard is no longer in progress.

2023-05-02 16:58 UTC, francisco-guilherme approved these changes

2023-05-02 18:28 UTC, merged