feat(TimePicker): implementation according to ds5 and ds3
lumada-design/hv-uikit-react pull request #3407
Opened 2023-06-05 17:58 UTC by zettca

WIP description

2023-06-06 09:56 UTC, plagoa commented
@zettca the `QueryBuilder` component is missing the `TimePicker` to be completed. Can it be included here?

2023-06-14 16:37 UTC, plagoa approved these changes

2023-06-14 21:13 UTC, francisco-guilherme commented
There's a styling issue when switching do DS3 theme.

Actual:
<img width="230" alt="Screenshot 2023-06-14 at 22 11 00" src="https://github.com/lumada-design/hv-uikit-react/assets/14975353/d0bd036d-2689-4415-bf77-f0cebdd95d1b">

v4.x
<img width="222" alt="Screenshot 2023-06-14 at 22 12 29" src="https://github.com/lumada-design/hv-uikit-react/assets/14975353/61d33798-e00f-47d0-a6eb-7400a45cea4d">

2023-06-14 21:14 UTC, francisco-guilherme requested changes
There's a styling issue when switching do DS3 theme.

Actual:
<img width="230" alt="Screenshot 2023-06-14 at 22 11 00" src="https://github.com/lumada-design/hv-uikit-react/assets/14975353/d0bd036d-2689-4415-bf77-f0cebdd95d1b">

v4.x
<img width="222" alt="Screenshot 2023-06-14 at 22 12 29" src="https://github.com/lumada-design/hv-uikit-react/assets/14975353/61d33798-e00f-47d0-a6eb-7400a45cea4d">

2023-06-16 15:48 UTC, plagoa approved these changes

2023-06-16 16:44 UTC, francisco-guilherme approved these changes

2023-06-16 16:44 UTC, merged