fix(DropdownMenu): add variant prop to be inline with other components
lumada-design/hv-uikit-react pull request #3996
Opened 2024-01-26 17:55 UTC by HQFOX

It doesn't make much sense that this component has a prop categories while others have variants and the values are the same.

category was marked as deprecated and not remove to not cause breaking changes

2024-01-29 09:39 UTC, zettca approved these changes

2024-01-30 09:14 UTC, MEsteves22 requested changes

2024-01-30 09:14 UTC, MEsteves22 commented on packages/core/src/DropDownMenu/DropDownMenu.tsx
> +    variant = "secondaryGhost",
If the user doesn't use the new `variant` and it's still using `category`, the default value for the `variant` property will always override the value set for `category`. I believe not setting a default value for `variant` should fix this for now.

2024-02-06 09:07 UTC, MEsteves22 approved these changes

2024-02-06 09:07 UTC, merged